# To change metadata used for Hyrax::PcdmCollections...
#
# add fields - see /config/metadata/collection_metadata.yaml
#
# remove or modify field
# * copy this file to your app in the same location
# * edit copied file
# * remove the entire field definition to remove the field completely from collection resources
# * modify any part of the field definition to change the characteristics of a field
#
# @note A definition in this file cannot be overridden by adding the same field to
#   the collection_metadata.yaml.  This will cause an error.
#
# @note To remove all basic metadata, set this file to `attributes: {}`.
#
# @note ActiveFedora::Base Collections use a different process for metadata.
#   In this case, a Collection class is generated when the Hyrax app generator
#   is run.  In the generated class…
# * includes `Hyrax::CollectionBehavior` which includes `Hyrax::CoreMetadata`
# * includes `Hyrax::BasicMetadata`
#
attributes:
  description:
    type: string
    multiple: true
    form:
      primary: true
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
  creator:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "creator_tesim"
  contributor:
    type: string
    multiple: true
    form:
      primary: false
  keyword:
    type: string
    multiple: true
    index_keys:
      - "keyword_sim"
      - "keyword_tesim"
    form:
      primary: false
  license:
    type: string
    multiple: true
    form:
      primary: false
  publisher:
    type: string
    multiple: true
    form:
      primary: false
  date_created:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_created_tesim"
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: false
  language:
    type: string
    multiple: true
    form:
      primary: false
  identifier:
    type: string
    multiple: true
    form:
      primary: false
  based_near:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "based_near_sim"
      - "based_near_tesim"
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_tesim"
  resource_type:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
